### ISSUE TITLE
Error loading  - 2022.3

### ISSUE THREAD

**Issue by JB-Encrypt** [DurgNomis-drol/DMI_pollen#2]
Platform error sensor.dmi_pollen - cannot import name 'HTTP_OK' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

Gets this error when trying to validate config before restart. 
No workaround beyond disabling the module.

**Comment by DurgNomis-drol** [comment]
Should be fixed in the latest master 😃

**Comment by stofakiller** [comment]
Just installed it on a fresh on 2022.3.4

Also get the same error: Platform error sensor.dmi_pollen - cannot import name 'HTTP_OK' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

**Comment by DurgNomis-drol** [comment]
Sorry, forgot to remove the import line. Please try again

**Comment by stofakiller** [comment]
Downloaded the new files, and now i can restart HA, thanks...
