### ISSUE TITLE
Change to HA attribute assignment gives error in logs

### ISSUE THREAD

**Issue by JB-Encrypt** [DurgNomis-drol/DMI_pollen#3]
In the newer versions HA has changes the way to assign attributes. 

Entity sensor.dmi_pollen_kobenhavn (<class 'custom_components.dmi_pollen.sensor.PollenSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.dmi_pollen_viborg (<class 'custom_components.dmi_pollen.sensor.PollenSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by DurgNomis-drol** [comment]
Should also be fix now

**Comment by JB-Encrypt** [comment]
Verified working. If everyone in the world work as fast as you there would be world peace :D Thank you.
